version: "3.4"

services:
  # django:
  #   container_name: django
  #   image: python:3.8
  #   working_dir: /app
  #   command: ['pip3', 'install', '-r', 'requirements.txt']
  #   volumes:
  #     - ./myDjangoProject/:/app/


  postgres:
    container_name: postgres
    image: postgres:14.4-bullseye
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypass
  psql:
    container_name: psql
    image: postgres:14.4-bullseye
    command: [ 'sleep', '86400' ]

  mongodb:
    container_name: mongodb
    image: mongo:6.0.2
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

volumes:
  postgres-volume: {}
  mongo-volume: {}
