# Generated by Django 4.0.6 on 2022-07-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_players', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ticket_price', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('google_map_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='shuttleBudd_name_d2dc3f_idx'),
        ),
        migrations.AddField(
            model_name='socialgame',
            name='courts',
            field=models.ManyToManyField(to='shuttleBuddy.court'),
        ),
        migrations.AddField(
            model_name='socialgame',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuttleBuddy.venue'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['username'], name='shuttleBudd_usernam_93af96_idx'),
        ),
        migrations.AddField(
            model_name='court',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuttleBuddy.venue'),
        ),
        migrations.AddField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuttleBuddy.court'),
        ),
        migrations.AddField(
            model_name='booking',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuttleBuddy.player'),
        ),
        migrations.AddField(
            model_name='booking',
            name='social_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuttleBuddy.socialgame'),
        ),
        migrations.AddIndex(
            model_name='socialgame',
            index=models.Index(fields=['name'], name='shuttleBudd_name_c69415_idx'),
        ),
        migrations.AddIndex(
            model_name='socialgame',
            index=models.Index(fields=['date'], name='shuttleBudd_date_1f99b1_idx'),
        ),
        migrations.AddIndex(
            model_name='socialgame',
            index=models.Index(fields=['time'], name='shuttleBudd_time_8c79ed_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['name'], name='shuttleBudd_name_edd0cb_idx'),
        ),
    ]
