# Generated by Django 4.0.6 on 2022-10-07 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleBuddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialGameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weekday', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuttleBuddy.venue')),
            ],
        ),
        migrations.AddIndex(
            model_name='socialgameevent',
            index=models.Index(fields=['name'], name='shuttleBudd_name_6cade1_idx'),
        ),
    ]
