apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucky-birdie
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: lucky-birdie
  template:
    metadata:
      labels:
        app: lucky-birdie
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: telegram-bot
          image: ghcr.io/raynix/shuttle-buddy:dev-5408234322
          envFrom:
            - secretRef:
                name: lucky-birdie-env
          env:
            - name: PROD
              value: 'true'
          ports:
            - name: webhook
              containerPort: 8000
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
          livenessProbe:
            tcpSocket:
              port: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
