apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  ports:
    - name: webhook
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: lucky-birdie
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: webhook
spec:
  gateways:
    - istio-system/awes-gateway
  hosts:
    - luckybirdie.awes.one
  http:
    - route:
      - destination:
          host: webhook
          port:
            number: 8000
