# Generated by Django 4.0rc1 on 2021-12-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleBuddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ticket_price', models.IntegerField(default=12)),
                ('courts', models.ManyToManyField(to='shuttleBuddy.Court')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuttleBuddy.venue')),
            ],
        ),
    ]
