# Generated by Django 4.0rc1 on 2021-12-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleBuddy', '0003_player_booking'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['name'], name='shuttleBudd_name_edd0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['username'], name='shuttleBudd_usernam_93af96_idx'),
        ),
        migrations.AddIndex(
            model_name='socialgame',
            index=models.Index(fields=['name'], name='shuttleBudd_name_c69415_idx'),
        ),
        migrations.AddIndex(
            model_name='socialgame',
            index=models.Index(fields=['date'], name='shuttleBudd_date_1f99b1_idx'),
        ),
        migrations.AddIndex(
            model_name='socialgame',
            index=models.Index(fields=['time'], name='shuttleBudd_time_8c79ed_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='shuttleBudd_name_d2dc3f_idx'),
        ),
    ]
